### ISSUE TITLE
Deleted messages make the thread scraping process crash

### ISSUE THREAD

**Issue by Flood1993** [Flood1993/eol_scraper#1]
```
>>> from eolscraper import EOLScraper
>>> s = EOLScraper()
>>> s.create_browser_session(visual=True)
>>> s.scrape_thread_from_scratch('https://www.elotrolado.net/hilo_detenido-el-presidente-de-la-diputacion-de-valencia-por-cargos-a-dedo_2291558', 47)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/guimo/code/eol_scraper/eolscraper.py", line 94, in scrape_thread_from_scratch
    message = extract_message_from_date_element(d)
  File "/home/guimo/code/eol_scraper/eolmessage.py", line 55, in extract_message_from_date_element
    content = date_element.find_element_by_xpath('../../../../div[3]/div').text
  File "/home/guimo/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 351, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/guimo/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 653, in find_element
    {"using": by, "value": value})['value']
  File "/home/guimo/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "/home/guimo/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 314, in execute
    self.error_handler.check_response(response)
  File "/home/guimo/miniconda3/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"../../../../div[3]/div"}
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.40.565383 (76257d1ab79276b2d53ee976b2c3e3b9f335cde7),platform=Linux 4.15.0-23-generic x86_64)
>>> len(s.thread.messages)
41
>>> s.thread.messages[0].author
'jorcoval'
>>> s.thread.messages[-1].author
'jorcoval'
```

**Comment by Flood1993** [comment]
Should be fixed in ac85a4faa343e4ec6cce3f78942629fc4b974441
